# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Free Trial(bcfbc7b2-92f5-4d66-8143-ffd98d46685d)'
    appType: 'webAppLinux'
    appName: 'azwebappHelloWorld'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    runtimeStack: 'JAVA|8-jre8'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
